mybooksproject/mybooksapp/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name='mybooksapp'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:booklist_id>/', views.detail_list, name='detail_list'),
    path('detail_genre/<int:list_id>/<int:bookgenre_id>/', views.detail_genre, name='detail_genre'),
    path('detail_book/<int:book_id>/', views.detail_book, name='detail_book'),
    path('new_book/', views.new_book, name='new_book'),
    path('delete_book/<int:book_id>/', views.delete_book, name='delete_book'),
    path('update_book/<int:book_id>', views.update_book, name='update_book'),
    path('search/', views.search, name='search'),
]

mybooksproject/mybooksproject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('mybooksapp/', include('mybooksapp.urls'))
]

mybooksproject/mybooksapp/models.py
from django.db import models

# Create your models here.

class BookList(models.Model):
    name = models.CharField(max_length=50)
    icon = models.CharField(max_length=100, default=True)

    def __str__(self):
            return f'{self.name}'

class BookGenre(models.Model):
    name = models.CharField(max_length=50)
    icon = models.CharField(max_length=100, default=True)

    def __str__(self):
            return f'{self.name}'

class Book(models.Model):
    title = models.CharField(max_length=50)
    author = models.CharField(max_length=50)
    content = models.CharField(max_length=1500)
    rating = models.IntegerField(default=0, null=False)
    done = models.BooleanField(default=False, null=False)
    price = models.DecimalField(max_digits=7, decimal_places=2, default=0.00, null=False)
    cover = models.CharField(max_length=200)
    booklist = models.ForeignKey(BookList, on_delete=models.CASCADE)
    genre = models.ForeignKey(BookGenre, on_delete=models.CASCADE)

    def __str__(self):
            return f'{self.title} {self.author} {self.content} {self.rating} {self.done} {self.price} {self.cover} {self.booklist} {self.genre}'

mybooksproject/mybooksapp/views.py
from django.shortcuts import get_object_or_404, render, redirect
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from .models import BookList, BookGenre, Book
from bs4 import BeautifulSoup
import requests

def index(request):
    listen = BookList.objects.all()
    return render(request, 'mybooksapp/index.html', {'listen':listen})

def detail_list(request, booklist_id):
    liste = get_object_or_404(BookList, pk=booklist_id)
    genres = BookGenre.objects.all()
    return render(request, 'mybooksapp/detail_list.html', {'liste':liste, 'genres':genres, 'list_id':booklist_id})

def detail_genre(request, list_id, bookgenre_id):
    genres = BookGenre.objects.all()
    genre = get_object_or_404(BookGenre, pk=bookgenre_id)
    books = Book.objects.filter(genre=bookgenre_id, booklist=list_id)
    return render(request, 'mybooksapp/detail_genre.html', {'genre':genre, 'books':books})

def detail_book(request, book_id):
    book = get_object_or_404(Book, pk=book_id)
    return render(request, 'mybooksapp/detail_book.html', {'book':book})

def get_thalia_data(thalia_id):
    # https://www.thalia.de/shop/home/artikeldetails/ID147880463.html

    # Schritt 2: Wir holen alles was wir brauchen aus der Seite von Thalia.
    url = f"https://www.thalia.de/shop/home/artikeldetails/ID{thalia_id}.html"
    response = requests.get(url)
    soup = BeautifulSoup(response.text, 'html.parser')
    data = {}
    data["cover"] = soup.select_one("img.largeImg").attrs["src"]
    data["title"] = soup.select_one("h1.ncTitle").string.strip()
    data["author"] = soup.select_one("p.aim-author").get_text().strip()
    data["content"] = soup.select_one("div.beschreibung div.text-infos").get_text().strip()
    data["rating"] = len(soup.select(".main .rating-star.active"))
    euro = soup.select_one(".mainPrice .oPriceLeft").string.strip()
    cent = soup.select_one(".mainPrice .oPriceRight").string.strip()
    data["price"] = float(f"{euro}.{cent}")
    print(f"Data: {data}")
    return data

def get_thalia_id(isbn):
    # https://www.thalia.de/suche?filterPATHROOT=&sq=9783426281550

    # Schritt 1: Wir schauen, ob es ein Buch zur ISBN gibt 
    # und wie die Thalia ID zu dem Buch ist.
    url = f"https://www.thalia.de/suche?filterPATHROOT=&sq={isbn}"
    response = requests.get(url)
    soup = BeautifulSoup(response.text, 'html.parser')
    result = soup.select_one("li.suchergebnis")
    if result == None:
        print(f"Keine Ergebnisse bei Thalia für ISBN {isbn}")
        return None
    id = result.attrs["data-id"]
    print(f"ID für ISBN {isbn}: {id}")
    return id

def new_book(request):
    data = {}
    if request.method == 'POST':
        # Formular zur manuellen Eingabe
        if "anlegen" in request.POST:
            title = request.POST["title"]
            author = request.POST["author"]
            content = request.POST["content"]
            rating = request.POST["rating"]
            price = request.POST["price"]
            cover = request.POST["cover"]
            booklist = BookList.objects.get(pk=request.POST["booklist"])
            genre = BookGenre.objects.get(pk=request.POST["genre"])
            Book.objects.create(title=title,
                                author=author,
                                content=content,
                                rating=rating,
                                price=price,
                                cover=cover,
                                booklist=booklist,
                                genre=genre,)
            return HttpResponseRedirect(reverse('mybooksapp:detail_list', args=[booklist.id]))
        if "isbnsuche" in request.POST:
            thalia_id = get_thalia_id(request.POST["isbn"])
            if thalia_id:
                data = get_thalia_data(thalia_id)
    
    return render(request, 'mybooksapp/new_book.html', {"booklists": BookList.objects.all(), "genres": BookGenre.objects.all(), "data": data})

def delete_book(request, book_id):
    book = get_object_or_404(Book, pk=book_id)
    book.delete()
    return HttpResponseRedirect(reverse('mybooksapp:index'))

def update_book_def(book, post):
    if "book_title" in post:
        book.title = post["book_title"]
    if "book_author" in post:
        book.author = post["book_author"]
    if "book_content" in post:
        book.content = post["book_content"]    
    if "book_rating" in post:
        try:
            rating = int(post["book_rating"]) 
        except ValueError:
            rating = 0
        book.rating = rating
    book.done = "book_done" in post
    if "book_price" in post:
        try:
            price = float(post["book_price"]) 
        except ValueError:
            price = 0
        book.price = price
    if "book_cover" in post:
        book.cover = post["book_cover"]
    if "book_booklist" in post:
        book.booklist = get_object_or_404(BookList, pk=post["book_booklist"])
    if "book_genre" in post:
        book.genre = get_object_or_404(BookGenre, pk=post["book_genre"])
    book.save()


def update_book(request, book_id):
    book = get_object_or_404(Book, pk=book_id)
    if request.POST:
        update_book_def(book, request.POST)
        return HttpResponseRedirect(reverse('mybooksapp:detail_book', args=[book.id]))
    listen = BookList.objects.all()
    genres = BookGenre.objects.all()
    context = {
            "listen": listen, 
            "genres": genres, 
            "book": book, 
            }
    return render(request, "mybooksapp/update_book_def.html", context)

def search(request):
    if request.POST:
        if "search_author" in request.POST:
            suche = request.POST["search_author"]
            books = Book.objects.filter(author__contains=suche)
            return render(request,"mybooksapp/search.html",{"books":books})
        
        if "search_title" in request.POST:
            suche = request.POST["search_title"]
            books = Book.objects.filter(title__contains=suche)
            return render(request,"mybooksapp/search.html",{"books":books})

    else:
        return render(request, "mybooksapp/search.html", {})
        

mybooksproject/mybooksapp/templates/mybooksapp/detail_book.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'mybooksapp/style.css' %}">
    <title>{{book.title}}</title>
</head>
<body>

    <div class='row justify-content-md-center p-2 mt-5'>
    <div class="col-lg-10 p-4 bg-white rounded shadow-sm">   

        <div class='container d-flex'>
            <img src="{{book.cover}}" class="" alt="image">
            <div class='pl-4'>
                <h2>{{book.title}}</h2>
                <p>{{book.content}}</p>
                <p><b>Autor: </b>{{book.author}}</p>
                <p><b>Bewertung: </b>{{book.rating}}</p>
                <p><b>Gelesen: </b>{{book.done}}</p>
                <p><b>Preis: </b>{{book.price}}</p>
                <p><b>Genre: </b>{{book.genre}}</p>
                <div class='mt-4'>
                    <a href="{% url 'mybooksapp:update_book' book.id%}" class='btn'>Bearbeiten</a>
                    <a href="{% url 'mybooksapp:delete_book' book.id%}" class='btn'>Löschen</a>
                </div>
            </div>
        </div>
    
    </div>
    </div>

</body>
</html>

mybooksproject/mybooksapp/templates/mybooksapp/detail_genre.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    {% load static %}
    <link href="{% static 'mybooksapp/images' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'mybooksapp/style.css' %}">
    <title>{{liste.name}}</title>
</head>
<body>

    <div class="d-flex justify-content-start flex-wrap">
        {%for book in books%}
        <div class="container text-center" style="width: 13.9rem;">
            <div class="card m-3" style="width: 10rem;">
                <img src="{{book.cover}}" class="card-img-top" alt="image" height="250px">
            </div>
            <a href="{% url 'mybooksapp:detail_book' book.id%}" class="btn" style="width: 10rem;">Zum Buch</a>
        </div>
        {%endfor%}
    </div>

    <div class='mt-5'>
        <button type="button" class="btn"><a href="{% url 'mybooksapp:new_book' %}" class='text-light'>+ Neues Buch hinzufügen</a></button>
    </div>

</body>
</html>

mybooksproject/mybooksapp/templates/mybooksapp/detail_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    {% load static %}
    <link href="{% static 'mybooksapp/images' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'mybooksapp/style.css' %}">
    <title>{{liste.name}}</title>
</head>
<body>

     <a href="{% url 'mybooksapp:index'%}" class='text-dark'>
        <svg width="2em" height="2em" viewBox="0 0 16 16" class="bi bi-arrow-left-square" fill="black" xmlns="http://www.w3.org/2000/svg">
        <path fill-rule="evenodd" d="M14 1H2a1 1 0 0 0-1 1v12a1 1 0 0 0 1 1h12a1 1 0 0 0 1-1V2a1 1 0 0 0-1-1zM2 0a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2H2z"/>
        <path fill-rule="evenodd" d="M12 8a.5.5 0 0 1-.5.5H5.707l2.147 2.146a.5.5 0 0 1-.708.708l-3-3a.5.5 0 0 1 0-.708l3-3a.5.5 0 1 1 .708.708L5.707 7.5H11.5a.5.5 0 0 1 .5.5z"/>
        </svg>Zurück zur Startseite
    </a>

    <div class='justify-content-md-center'>
    <div class="d-flex justify-content-start flex-wrap">
        {%for genre in genres%}
            <div class="p-4 m-3 bg-white rounded shadow-sm text-center">
                <img src="{% static genre.icon %}" alt="image"></br>
                <a href="{% url 'mybooksapp:detail_genre' list_id genre.id%}" class="btn mt-1">{{ genre.name }}</a></br>
            </div>
        {%endfor%}

    </div>
    </div>
  
</body>
</html>

mybooksproject/mybooksapp/templates/mybooksapp/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    {% load static %}
    <link href="{% static 'mybooksapp/images' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'mybooksapp/style.css' %}">
    <title>MyBooks</title>
</head>
<body>

    <div class='row justify-content-md-center p-2 pt-5 mt-5'>
        {% for list in listen%}
            <a href="{% url 'mybooksapp:detail_list' list.id%}"><img src="{% static list.icon %}" alt="image"></a>
        {% endfor %}
    </div>

    <div class='row justify-content-md-center p-2 mt-2'>
        <a href="{% url 'mybooksapp:search'%}" class='btn btn-light'>Suche</a>
    </div>

</body>
</html>

mybooksproject/mybooksapp/templates/mybooksapp/new_book.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'mybooksapp/style.css' %}">
    <title>Neues Buch hinzufügen</title>
</head>
<body>

  <div class='row justify-content-md-center p-2 mt-5'>
  <div class="col-lg-10 p-4 bg-white rounded shadow-sm">

    <form action="" method="post">
    <div class="form-group">
      {% csrf_token %}
      <label>Titel</label>
      <input type="text" name="title"{% if "title" in data %} value="{{ data.title }}"{% endif %}><br>

      <label>Autor:in</label>
      <input type="text" name="author"{% if "author" in data %} value="{{ data.author }}"{% endif %}><br>

      <label>Inhalt</label>
      <input type="textarea" name="content"{% if "content" in data %} value="{{ data.content }}"{% endif %}><br>

      <label>Bewertung</label>
      <input type="number" name="rating"{% if "rating" in data %} value="{{ data.rating }}"{% endif %}><br>

      <label>Preis</label>
      <input type="number" step="0.01" name="price"{% if "price" in data %} value="{{ data.price }}"{% endif %}><br>

      <label>Cover</label>
      <input type="text" name="cover"{% if "cover" in data %} value="{{ data.cover }}"{% endif %}><br>

      <label>Bücherliste</label>
      <select name="booklist">
        {% for list in booklists %}
          <option value="{{list.id}}">{{list}}</option>
        {% endfor %}
      </select></br>

      <label>Genre</label>
      <select name="genre">
        {% for genre in genres %}
          <option value="{{genre.id}}">{{genre}}</option>
        {% endfor %}
      </select></br>

      <div class="input-group">
        <input class="btn" type="submit" name="anlegen" value="Speichern">
      </div>

    </div>
    </form>

    <form action="{% url "mybooksapp:new_book" %}" method="post">
      <input type="text" name="isbn" id="isbn" value="9783426281550">
      {% csrf_token %}
      <input type="submit" name="isbnsuche" id="isbnsuche" value="Daten importieren">
    </form>

    <p>
    Beispiel-ISBNs: 9783426281550
    </p>
  
</form>

  </div>
  </div>

</body>
</html>

mybooksproject/mybooksapp/templates/mybooksapp/search.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    {% load static %}
    <link href="{% static 'mybooksapp/images' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'mybooksapp/style.css' %}">
    <title>Suche</title>
</head>
<body>

    <div class='row justify-content-md-center p-2 mt-5'>
    <div class="col-lg-10 p-4 bg-white rounded shadow-sm"> 
        <form action="" method="post" name="myform">
            <div class="form-group">
            {% csrf_token %}
            <input type="text" name="search_author" id="search" placeholder='Suche nach Autor'></br>
            <input type="text" name="search_title" id="search" placeholder='Suche nach Titel'>
            </div>

            <div class="input-group">
                <input class="btn" type="submit" name="anlegen" value="Suchen">
            </div>

        </form>
    </div>
    </div>

    {% if books %}
    {% for book in books %}
        <div class="container text-center" style="width: 13.9rem;">
            <div class="card m-3" style="width: 10rem;">
                <img src="{{book.cover}}" class="card-img-top" alt="image" height="250px">
            </div>
            <a href="{% url 'mybooksapp:detail_book' book.id%}" class="btn" style="width: 10rem;">Zum Buch</a>
        </div>
    {%endfor%}
    {%endif%}

</body>
</html>

mybooksproject/mybooksapp/templates/mybooksapp/update_book_def.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'mybooksapp/style.css' %}">
    <title>Buch bearbeitem</title>
</head>
<body>

    <div class='row justify-content-md-center p-2 mt-5'>
    <div class="col-lg-10 p-4 bg-white rounded shadow-sm">

        <form action="{% url 'mybooksapp:update_book' book.id %}" method="POST">
        <div class="form-group">
            {% csrf_token %}
            <label for="book_title">Titel</label>
            <input class="form-control" type="text" name="book_title" id="book_title" value="{{book.title}}"><br>

            <label for="book_author">Autor</label>
            <input class="form-control" type="text" name="book_author" id="book_author" value="{{book.author}}"><br>

            <label for="book_content">Inhalt</label>
            <input class="form-control" type="text" name="book_content" id="book_content" value="{{book.content}}"><br>

            <label for="book_rating">Bewertung</label>
            <input class="form-control" type="number" name="book_rating" id="book_rating" value="{{book.rating}}"><br>

            <label for="book_done">Gelesen</label>
            <input class="form-check" type="checkbox" name="book_done" id="book_done" value="{{book.done}}" {% if book.done %}checked{% endif %}><br>

            <label for="book_price">Preis</label>
            <input class="form-control" type="number" step="0.01" name="book_price" id="book_price" value="{{book.price}}"><br>

            <label for="book_cover">Cover</label>
            <input class="form-control" type="text" name="book_cover" id="book_cover" value="{{book.cover}}"><br>

            <label for="book_booklist">Liste</label>
            <select class="form-control" name="book_booklist" id="book_booklist">
                {% for liste in listen %}
                    <option value="{{liste.id}}" {% if liste == book.liste %}selected{% endif %}>{{liste.name}}</option> 
                {% endfor %}  
            </select><br>

            <label for="book_genre">Genre</label>
            <select class="form-control" name="book_genre" id="book_genre">
                {% for genre in genres %}
                    <option value="{{genre.id}}" {% if genre == book.genre %}selected{% endif %}>{{genre.name}}</option> 
                {% endfor %}  
            </select><br>

            <div class="input-group">
                <input class="btn" type="submit" value="Speichern">
            </div>
        </div>
        </form>

    </div>
    </div>

</body>
</html>